name: On pull request
on:
  pull_request:
    branches: [main]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Commitlint and Other Shared Build Steps
        uses: momentohq/standards-and-practices/github-actions/shared-build@gh-actions-v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verify README generation
        uses: momentohq/standards-and-practices/github-actions/oss-readme-template@gh-actions-v2
        with:
          project_status: official
          project_stability: beta
          project_type: sdk
          sdk_language: Swift
          template_file: ./README.template.md
          output_file: ./README.md
          dev_docs_slug: swift

  test:
    uses: ./.github/workflows/test.yml
    secrets:
      auth-token: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      github-token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}
