name: On push to main
on:
  push:
    branches: [main]

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

      - name: Generate README
        uses: momentohq/standards-and-practices/github-actions/generate-and-commit-oss-readme@gh-actions-v2
        with:
          project_status: official
          project_stability: alpha
          project_type: sdk
          sdk_language: Swift
          template_file: ./README.template.md
          output_file: ./README.md
          dev_docs_slug: swift
      
  test:
    needs: [readme]
    uses: ./.github/workflows/test.yml
    secrets:
      auth-token: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      github-token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: google-github-actions/release-please-action@v3
        name: Release Please
        id: release
        with:
          token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}
          release-type: simple
          package-name: client-sdk-swift
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'

      - name: Publish
        run: |
          echo "Published version: ${{ steps.release.outputs.tag_name }}"
        if: ${{ steps.release.outputs.release_created }}
